 CREATE TABLE IF NOT EXISTS parking (
    id INT AUTO_INCREMENT PRIMARY KEY,
    vehicle_no VARCHAR(50) NOT NULL,
    entry_time DATETIME NOT NULL,
    exit_time DATETIME DEFAULT NULL,
    fee INT DEFAULT NULL,
    status VARCHAR(20) DEFAULT 'parked'
);
